### PR TITLE
Add endpoint for cleaning long running workspaces

### PR DESCRIPTION
**Pull request by amisevsk**
Continuation of #26, but merging into master

### CODE REVIEW

**Comment by davidfestal** [comment]
let me copy / comment parts of the last discussions that occurred in PR #26:

>- @davidfestal :
>
>So finally we still need to have the Keycloak (OSIO) token of the user to do this cleaning.
>The alternate way (which is much less clean of course) would be to do the detection + stop at the pure OpenShift POD and DC level, without even looking into the user workspaces.
>I still think that this solution is better, but since we don't have a way to get short-living user OSIO token from the maintainer, that make it not easy to run it or automate it.
>
> @l0rd wdyt ?
>
>- @amisevsk :
>
>Both options here require a token, whether it's the user's token for accessing Che server, or a token with edit rights to a user's namespace. I'm not sure what the best way to do this is, short of having some sort of admin token for Che server.

When using the service account token, there might be a way to avoid requiring any *user token*: since we get the SA token at start, we then only need the *user ID* to access the user OS namespace. We already retrieve the user Id from the `identity-id` parameter if it exists, before trying to extract it from the user JWT token. So a user-specific OSIO token is only required to access the Che user account, at least when the Service Account token is used to access the OSO proxy.

>
>Also, stopping workspaces by deleting OpenShift resources has the issue that those workspaces will not be marked as stopped in the Che DB, and will be recovered on every start. In that sense I think it's important to interact with the server. 

Despite my above comment, I still also think it is the cleanest approach. However, in order to allow using the maintainer for regular (automatic ?) maintenance actions, we should have a way to have access to the user Che account without the need to manually request each user token. We could use one of the 2 solutions:
1. have the ability to retrieve, from a `fabric8_auth` service (protected by some secret or SA), a short-living OSIO user token based on a user ID, to be used in order to do actions in the user Che account. The corresponding `fabric8_auth` endpoint could also provide a way to invalidate the token as soon as it has been used. I already spoke a bit about this need to @sbose78.
2. use the Che admin user token (as soon as there will one available), but then this would require changing a bit the code to explicitly specify the Che user account in which Che API calls should occur (currently it is defined by the token itself).

I tend to prefer solution 1 since it seems more flexible and would still ensure that we always use a user-specific token to access the user Che account, without having unnecessary extended rights. 

@l0rd wdyt ?

**Comment by l0rd** [comment]
Soution 1) seams ideal but harder to implement. So I would rather wait for 2) and, in the meantime, ask SD team to manually run the maintainer once a week (using users tokens). cc @ibuziuk

**Comment by amisevsk** [comment]
@davidfestal Should we merge this PR as is, and address the issue of getting user tokens elsewhere?

**Comment by davidfestal** [comment]
Sure. I think so.

**Pull request merged**
